// 文档站场景配置 —— 特点：新手能看懂/搜索/可读性 是核心
export default {
  name: "我的文档站",
  siteUrl: "http://localhost:3000",
  workDir: ".",
  memoryDir: "reports/iterate",
  dims: [
    { k: 'D', name: '任务完成', q: '用户能否找到答案/完成任务', veto: false },
    { k: 'C', name: '内容质量', q: '文档是否准确/最新/可读', veto: false },
    { k: 'M', name: '变现', q: '引流到付费/试用转化', veto: false },
    { k: 'T', name: '数据可信', q: '版本号/API 参数/示例是否可验证', veto: true, vm: 4 },
    { k: 'R', name: '合规', q: '免责/许可证/教程风险', veto: true, vm: 4 },
    { k: 'S', name: '可维护', q: '文档更新维护成本低', veto: true, vm: 3 },
    { k: 'F', name: '目标一致', q: '是否服务核心目标（用户会用起来）', veto: true, vm: 1 },
    { k: 'P', name: '性能', q: '文档页加载/搜索速度', veto: false },
    { k: 'U', name: '体验', q: '导航/代码高亮/移动端', veto: false },
    { k: 'G', name: '增长', q: 'SEO/社区分发', veto: false },
  ],
  extremeWords: ['最大', '最强', '最好', 'no.1', 'the best', 'leading', '唯一', '最简单'],
  roles: [
    {
      key: 'doc-reader', name: '文档读者', w: { D: 3 }, scope: ['all'],
      identity: '跟着文档动手做的新手：从入门页到跑通一个 demo。对“写了但跑不通”极敏感。',
      vision: '我按文档一步步操作：命令能否复制、示例能否跑通、版本是否一致。',
      checklist: '①入门路径是否清晰 ②命令/代码能否复制即用 ③示例与当前版本是否一致 ④报错是否有排查引导 ⑤搜索能否命中',
      kpi: '发现“照文档做不通”的。',
      constitution: '可复现（教程必须能跑通）·数据可信',
      defense: '别把“文档不够详尽”当缺点。只报“照做会失败”的。',
    },
    {
      key: 'maintainer', name: '维护者', w: { S: 3 }, scope: ['all'], judge: true, veto: 'S',
      identity: '站点的唯一维护者。评估这条改动让我每天多花几分钟。',
      vision: '可持续性：文档要人工同步吗？会成负担吗？',
      checklist: '①维护成本 ②数据源稳定 ③自动化空间 ④失败风险 ⑤值不值',
      kpi: '驳回高维护改动。',
      constitution: '单人可持续',
      defense: '别把一次性配置当高维护。',
    },
  ],
  pageCore: [
    { id: 'home', path: '/', name: '首页' },
    { id: 'getting-started', path: '/docs/getting-started', name: '入门' },
    { id: 'quickstart', path: '/docs/quickstart', name: '快速开始' },
    { id: 'api', path: '/docs/api', name: 'API' },
    { id: 'tutorial', path: '/docs/tutorial', name: '教程' },
    { id: 'blog', path: '/blog', name: '博客' },
    { id: 'about', path: '/about', name: '关于' },
  ],
  modelTiers: [
    { tier: 'T1', hint: '从导航挑一个最核心的教程页', n: 8 },
    { tier: 'T2', hint: '从侧边栏挑一个普通参考页', n: 6 },
    { tier: 'T3', hint: '从底部挑一个旧/废弃页', n: 3 },
  ],
  pageLongtail: [
    { id: 'lt-api-ref', name: 'API参考', path: '/docs/api/ref' },
    { id: 'lt-faq', name: 'FAQ', path: '/docs/faq' },
    { id: 'lt-troubleshoot', name: '排查', path: '/docs/troubleshooting' },
    { id: 'lt-changelog', name: '更新日志', path: '/changelog' },
    { id: 'lt-404', name: '404页', path: '/nonexistent' },
  ],
}
