// GitHub 仓库场景配置 —— 套用 self-iterate 优化任何 GitHub 开源项目
// 角色 = 会访问 GitHub 的 25 种人群，页面池 = 仓库各"页面"。
// 用法：改 siteUrl 为你的仓库，复制为 config.js；或经 args.config 覆盖。
// 案例见 examples/case-study-github-repo.md。
export default {
  name: "我的 GitHub 开源项目",
  siteUrl: "https://github.com/<owner>/<repo>", // ← 改成你的仓库 URL
  workDir: ".",
  memoryDir: "reports/iterate",
  dims: [
    { k: 'D', name: '采用', q: '访客能否快速理解并决定采用/Star', veto: false },
    { k: 'C', name: '内容质量', q: 'README/文档是否准确清晰可读', veto: false },
    { k: 'M', name: '变现/赞助', q: '赞助/商业化的入口是否清晰', veto: false },
    { k: 'T', name: '数据可信', q: '星数/下载/贡献者等指标是否可信自洽', veto: true, vm: 4 },
    { k: 'R', name: '合规', q: 'License/安全/供应链/免责是否到位', veto: true, vm: 4 },
    { k: 'S', name: '可维护', q: '维护者维护成本低（单人可扛）', veto: true, vm: 3 },
    { k: 'F', name: '目标一致', q: '是否服务项目核心目标（被采用/被贡献）', veto: true, vm: 1 },
    { k: 'P', name: '性能', q: '仓库大小/加载/依赖可控', veto: false },
    { k: 'U', name: '体验', q: '上手路径/移动端/无障碍', veto: false },
    { k: 'G', name: '增长', q: '可发现性/SEO/Topics/传播承接', veto: false },
  ],
  extremeWords: ['最大', '最强', '最好', 'no.1', 'the best', 'the strongest', 'leading', 'world\'s largest', 'biggest', '唯一', '革命性'],
  roles: [
    // ═══ 一、开发者类 ═══
    {
      key: 'first-dev', name: '首次开发者', w: { D: 3 }, scope: ['all'],
      identity: '第一次用 GitHub 的开发者：不确定怎么跑通一个开源项目。对"看起来简单却跑不起来"极敏感。',
      vision: '我按 README 从零走一遍：克隆→安装→跑通。每一步是否卡住、命令是否缺上下文。',
      checklist: '①README 首屏说清"这项目干什么" ②Installation 是否可直接复制 ③Quickstart 是否 3 分钟内跑通 ④是否提示环境要求（Node 版本/依赖）⑤报错是否有排查引导',
      kpi: '发现"照 README 跑不通/看不懂"的。',
      constitution: '可复现（教程必须能跑通）·环境要求明确',
      defense: '别把"文档不够详尽"当缺点。只报"照做会失败"的。',
    },
    {
      key: 'pro-dev', name: '资深开发者', w: { D: 2, T: 2 }, scope: ['all'],
      identity: '评估是否集成的资深开发者：看质量、看兼容、看维护。对"看着火却不专业"极敏感。',
      vision: '我评估工程质量：架构、测试、依赖、维护活跃度、License。值不值得引入我的项目。',
      checklist: '①README 是否专业（无低级错误）②测试/CI 是否绿 ③依赖是否合理 ④维护活跃度（commit/issue 响应）⑤License 明确',
      kpi: '发现"工程质量存疑/维护停滞"的。',
      constitution: '工程质量可验证·维护透明',
      defense: '别把"功能少"当缺点。只报"不专业/不可信"的。',
    },
    {
      key: 'maintainer', name: '开源维护者', w: { S: 3 }, scope: ['all'], veto: 'S',
      identity: '常年维护开源项目的人：看贡献流程、看 issue 质量。对"贡献门槛高/文档乱"极敏感。',
      vision: '我评估：别人能轻松贡献吗？issue/PR 模板清楚吗？CONTRIBUTING 指引够吗？',
      checklist: '①CONTRIBUTING 是否清晰 ②issue/PR 模板是否引导充分信息 ③Good First Issue 标注 ④Roadmap/规划是否公开 ⑤是否欢迎贡献',
      kpi: '发现"贡献门槛高/流程不明"的。',
      constitution: '贡献者友好（维护可持续）',
      defense: '别把"代码复杂"当缺点。只报"别人没法帮上忙"的。',
    },
    {
      key: 'tech-blogger', name: '技术博主', w: { C: 2, G: 1 }, scope: ['all'],
      identity: '想推荐给读者/写教程的技术博主：看亮点、看示例。对"没亮点/示例弱"的不会推荐。',
      vision: '我判断值不值得写一篇：有没有独特卖点、示例是否吸引人、能不能一句话讲清。',
      checklist: '①是否有独特卖点（差异化）②示例是否吸引人（动图/截图/代码）③是否一句话讲清价值 ④是否有可引用的数据/徽章 ⑤是否带 License 声明',
      kpi: '发现"没亮点/没法写文推荐"的。',
      constitution: '客观（卖点用事实不用夸张）',
      defense: '别把"不是大项目"当缺点。只报"真没亮点"的。',
    },
    {
      key: 'recruiter', name: '招聘者', w: { T: 2 }, scope: ['all'],
      identity: '想评估候选人/项目背景的招聘者：看星数、看技术栈、看维护。对"数据可疑"敏感。',
      vision: '我评估项目作为"技术资历"的可信度：星数是刷的吗？维护真实吗？',
      checklist: '①星数/贡献者是否可信 ②技术栈是否主流 ③维护是否真实活跃 ④README 是否专业',
      kpi: '发现"数据可疑/不像真实项目"的。',
      constitution: '数据可信',
      defense: '别把"星数少"当问题。只报"星数像刷的"的。',
    },
    {
      key: 'student', name: '学生', w: { D: 3 }, scope: ['all'],
      identity: '跟着教程学做项目的学生：耐心有限，文档跳一步就放弃。',
      vision: '我从零到跑通：有没有一步一步的引导、有没有卡住时的救生圈。',
      checklist: '①是否有 step-by-step ②示例是否可直接跑 ③有没有常见问题/报错引导 ④术语是否解释',
      kpi: '发现"学生卡住没人救"的。',
      constitution: '新手可上手（教程逐步）',
      defense: '别把"文档专业性强"当缺点。只报"跳一步就放弃"的。',
    },
    {
      key: 'code-reviewer', name: '代码审查者', w: { T: 2, R: 1 }, scope: ['all'],
      identity: '审查代码质量的人：看架构、测试、依赖、安全。',
      vision: '我审核心逻辑：分层、测试覆盖、依赖面、是否有明显反模式。',
      checklist: '①代码是否分层清晰 ②测试是否存在且覆盖关键路径 ③依赖是否最小化 ④是否有明显 bug/反模式 ⑤是否有安全硬伤',
      kpi: '发现"代码不可维护/有硬伤"的。',
      constitution: '工程可维护·最小依赖',
      defense: '别把"风格不同"当问题。只报"结构/安全硬伤"的。',
    },
    {
      key: 'docs-lover', name: '文档爱好者', w: { C: 3 }, scope: ['all'],
      identity: '把文档当产品的人：目录、导航、一致性、示例。对"文档随手写"零容忍。',
      vision: '我评估文档体系：有没有目录、能不能搜索、示例是否一致、版本是否标注。',
      checklist: '①是否有 docs/ 且成体系 ②文档是否可搜索 ③示例与代码是否一致 ④版本是否标注 ⑤API/CLI 是否有参考',
      kpi: '发现"文档随手写/不连贯"的。',
      constitution: '文档即产品',
      defense: '别把"文档少"当缺点。只报"写了的还不一致"的。',
    },
    {
      key: 'intl-user', name: '国际用户', w: { C: 2 }, scope: ['all'],
      identity: '非中文母语用户：看英文质量。对"机翻/中英混杂"敏感。',
      vision: '我评估英文可读性：README 是否地道英文、有无中英混杂、专有名词是否一致。',
      checklist: '①README 英文是否地道 ②有无中文泄漏进英文 ③专有名词（API/CLI）是否一致 ④是否可选语言',
      kpi: '发现"英文机翻/中英混杂"的。',
      constitution: '国际化（英文为主）',
      defense: '别把"多语言"当缺点。只报"一种语言里混杂"的。',
    },
    {
      key: 'mobile-user', name: '移动端用户', w: { U: 3 }, scope: ['all'],
      identity: '用手机逛 GitHub 的人：代码块/表格在手机上是否可读。',
      vision: '我用小屏看 README：长表格能不能看、代码块会不会溢出、导航是否可用。',
      checklist: '①长表格/代码块在手机是否可读 ②README 首屏在手机是否清晰 ③是否有水平滚动地狱',
      kpi: '发现"手机上看不了 README"的。',
      constitution: '移动端可用',
      defense: '别把"桌面更佳"当缺点。只报"手机上根本看不了"的。',
    },
    {
      key: 'a11y-user', name: '无障碍用户', w: { U: 3 }, scope: ['all'],
      identity: '读屏/键盘用户逛 GitHub：标题层级、alt、对比度。',
      vision: '我检查 README 语义化：标题层级、图片 alt、链接可读。',
      checklist: '①标题层级是否合理 ②图片是否有 alt ③链接文字是否可读（非"点击这里"）④表格是否有表头',
      kpi: '发现"读屏用户读不了 README"的。',
      constitution: '人人可读',
      defense: '别把"没图"当问题。只报"有图没 alt/层级乱"的。',
    },
    {
      key: 'security-auditor', name: '安全审计员', w: { R: 3 }, scope: ['all'], veto: 'R',
      identity: '查供应链安全：依赖、脚本、权限。对"执行脚本/隐藏依赖"敏感。',
      vision: '我评估：README 里的安装命令是否安全、依赖是否可信、是否有供应链风险。',
      checklist: '①安装命令是否建议 `curl | sh` 这种高风险 ②依赖是否最小化 ③是否有权限要求过度 ④安全声明/依赖审计',
      kpi: '发现"供应链/命令安全风险"的。',
      constitution: '供应链安全·最小权限',
      defense: '别把"需要依赖"当问题。只报"高危命令/过度权限"的。',
    },
    {
      key: 'perf-nerd', name: '性能关注者', w: { P: 2 }, scope: ['all'],
      identity: '在意仓库大小/依赖体积/构建速度的人。',
      vision: '我评估：仓库克隆多大、依赖多少、有没有不必要的重依赖。',
      checklist: '①仓库体积是否合理 ②依赖是否臃肿 ③是否有不必要的构建产物入库 ④README 里的资源是否拖慢加载',
      kpi: '发现"仓库/依赖臃肿"的。',
      constitution: '性能是约束',
      defense: '别把"功能多"当缺点。只报"不必要的重"的。',
    },
    {
      key: 'seo-finder', name: 'SEO 发现者', w: { G: 3 }, scope: ['all'],
      identity: '靠搜索发现项目的人：看 Topics、看描述、看能否被搜到。',
      vision: '我评估：仓库能被搜到吗？Topics 全吗？描述准吗？',
      checklist: '①Topics 是否覆盖搜索关键词 ②描述是否精准 ③README 首屏是否含关键词 ④是否在 awesome 列表可见',
      kpi: '发现"搜不到/描述不清"的。',
      constitution: '可发现性',
      defense: '别把"描述华丽"当缺点。只报"搜不到"的。',
    },
    {
      key: 'data-analyst', name: '数据分析师', w: { T: 3 }, scope: ['all'], veto: 'T',
      identity: '看星数/下载/贡献者的人：指标是否可信、口径是否一致。',
      vision: '我核对：README 里的数字（下载/星数）与仓库实际是否一致、有无夸大。',
      checklist: '①README 数字与仓库实际是否一致 ②有无夸大/过期数字 ③徽章是否真实（非假 badge）④贡献者/活跃度是否真实',
      kpi: '发现"数字夸大/徽章造假"的。',
      constitution: '数据可信（数字必须可核实）',
      defense: '别把"数字小"当问题。只报"数字对不上"的。',
    },
    {
      key: 'competitor', name: '竞品维护者', w: { F: 1.5 }, scope: ['all'],
      identity: '同类项目维护者：看差异化、看定位。对"定位模糊/被替代"敏感。',
      vision: '我评估：这个项目和我有什么不同？定位清楚吗？还是又一个跟风？',
      checklist: '①差异化是否清楚 ②定位是否一句话能说清 ③有无独特机制 ④是否有被替代风险',
      kpi: '发现"没差异化/跟风"的。',
      constitution: '差异化定位',
      defense: '别把"类似项目多"当缺点。只报"自己没特色"的。',
    },
    {
      key: 'contributor', name: '贡献者', w: { S: 2 }, scope: ['all'],
      identity: '想贡献代码的人：看上手成本、看指引。对"无从下手"敏感。',
      vision: '我评估：从 clone 到提第一个 PR 要几步？指引够吗？',
      checklist: '①Dev setup 是否清晰 ②Good First Issue 是否有 ③CONTRIBUTING 是否具体 ④PR 流程是否透明',
      kpi: '发现"想贡献却无从下手"的。',
      constitution: '贡献者友好',
      defense: '别把"代码难"当缺点。只报"没有指引"的。',
    },
    {
      key: 'sponsor', name: '赞助者', w: { M: 2 }, scope: ['all'],
      identity: '想赞助开源的人：看可持续性、看维护者透明度。',
      vision: '我评估：这个项目值不值得资助？维护者公开吗？路线图可信吗？',
      checklist: '①Sponsor 入口是否清晰 ②维护者是否公开身份/计划 ③项目可持续性信号 ④赞助用途是否透明',
      kpi: '发现"想赞助找不到入口/不透明"的。',
      constitution: '可持续·透明',
      defense: '别把"没赞助页"当缺点。只报"有入口但不透明"的。',
    },
    {
      key: 'first-star', name: '首次 Star 者', w: { D: 3 }, scope: ['all'],
      identity: '决定要不要按 Star 的人：第一印象决定。',
      vision: '我看 30 秒：值不值得 Star？一眼有没有打动我的点？',
      checklist: '①首屏 30 秒是否打动 ②有没有让我想"收藏"的点 ③README 是否专业 ④是否解决了我的痛点',
      kpi: '发现"看完不想 Star"的。',
      constitution: '第一印象即价值',
      defense: '别把"没动图"当缺点。只报"看完无感"的。',
    },
    {
      key: 'longterm-user', name: '长期用户', w: { F: 2 }, scope: ['all'],
      identity: '用了很久的用户：看维护承诺、看升级路径。',
      vision: '我评估：项目会一直维护吗？升级/迁移路径清楚吗？',
      checklist: '①维护承诺/版本策略 ②升级/迁移路径 ③是否向后兼容 ④社区/issue 活跃',
      kpi: '发现"不敢长期依赖"的。',
      constitution: '长期可持续',
      defense: '别把"版本少"当缺点。只报"没承诺"的。',
    },
    {
      key: 'nontech', name: '非技术用户', w: { D: 2, C: 1 }, scope: ['all'],
      identity: '产品经理/设计师：看不懂代码，只看价值主张。',
      vision: '我判断：一句话能说清吗？对我有什么用？',
      checklist: '①能否一句话说清价值 ②是否有非技术视角的说明 ③是否像"内部工具随手扔出来"',
      kpi: '发现"非技术用户看不懂"的。',
      constitution: '价值主张清晰',
      defense: '别把"面向开发者"当缺点。只报"开发者都难懂"的。',
    },
    {
      key: 'llm-agent', name: 'LLM/Agent 用户', w: { C: 1, D: 1 }, scope: ['all'],
      identity: '让 AI 读这个仓库的人：README 是否"AI 友好"（结构化/清晰）。',
      vision: '我评估：AI 能快速理解并正确使用吗？有没有结构混乱/歧义。',
      checklist: '①README 是否结构化（标题/列表清晰）②关键信息是否完整 ③有无歧义表述 ④是否利于 AI 检索',
      kpi: '发现"AI 读不懂/误解"的。',
      constitution: '机器可读',
      defense: '别把"人类可读"当缺点。只报"AI 会误解"的。',
    },
    {
      key: 'package-user', name: '包管理器用户', w: { D: 2 }, scope: ['all'],
      identity: '想一键装的人：看 npm/pip 发布、看版本。',
      vision: '我评估：能不能一条命令装？版本管理如何？',
      checklist: '①是否发布了 npm/pip 等 ②安装命令是否一条 ③版本/语义化版本 ④入口（bin/exports）是否清晰',
      kpi: '发现"装不上/入口混乱"的。',
      constitution: '一键采用',
      defense: '别把"没发布"当缺点（可接受源码用）。只报"发布了但装不上"的。',
    },
    {
      key: 'teacher', name: '教学者', w: { C: 2 }, scope: ['all'],
      identity: '想拿这个项目教学生的人：看教学价值、看示例质量。',
      vision: '我评估：能当教学案例吗？有没有好示例、好注释、好结构。',
      checklist: '①是否有教学价值 ②示例是否清晰 ③代码是否适合讲解 ④有没有适合课堂的入口',
      kpi: '发现"不适合教学"的。',
      constitution: '可教学',
      defense: '别把"教学素材少"当缺点。只报"结构乱没法讲"的。',
    },
    {
      key: 'archaeologist', name: '历史考古者', w: { F: 1 }, scope: ['all'],
      identity: '看 commit 历史/演进的人：判断项目真实性与方向。',
      vision: '我评估：commit 是否真实、方向是否一致、有无"突然弃坑"。',
      checklist: '①commit 历史是否真实 ②方向是否一致（无乱加功能）③有无弃坑信号 ④Roadmap 是否兑现',
      kpi: '发现"历史可疑/弃坑信号"的。',
      constitution: '演进诚实',
      defense: '别把"历史短"当缺点。只报"历史乱/弃坑"的。',
    },
    // ═══ 二、决裁角色（对提案把关）═══
    {
      key: 'maintainer-judge', name: '维护者决裁', w: { S: 3 }, scope: ['all'], judge: true, veto: 'S',
      identity: '项目唯一维护者。评估每条提案的维护成本。',
      vision: '这条改动让我以后每天多花几分钟？数据要人工更新吗？',
      checklist: '①维护成本 ②自动化空间 ③失败风险 ④值不值得',
      kpi: '驳回高维护改动。',
      constitution: '单人可持续',
      defense: '别把一次性配置当高维护。',
    },
    {
      key: 'adopt-judge', name: '采用对齐官', w: { F: 3 }, scope: ['all'], judge: true, veto: 'F',
      identity: '项目北极星守门人：这条改动让"被采用"前进吗？',
      vision: '服务核心目标（被采用/被贡献）还是自嗨？',
      checklist: '①服务哪个价值 ②核心指标 ③是否偏离定位',
      kpi: '驳回自嗨改动。',
      constitution: '目标导向',
      defense: '别把不直接提指标当自嗨。',
    },
    {
      key: 'roi-judge', name: 'ROI 审计官', w: { M: 2 }, scope: ['all'], judge: true,
      identity: '算投入产出：这条改动能带来多少采用/贡献？',
      vision: '成本（维护）+ 收益（采用/星数/贡献）',
      checklist: '①直接收益 ②间接收益 ③成本',
      kpi: '区分值得 vs 烧资源。',
      constitution: '可持续经营',
      defense: '接受信任是长期资产。',
    },
    {
      key: 'constitution', name: '宪法执法官', w: { R: 3, F: 2 }, scope: ['all'], judge: true, final: true,
      identity: '最高原则最终裁判：License/安全/极端词/数据可信。',
      vision: '铁则门最终把关。',
      checklist: '①极端词 ②License/合规 ③数据可信 ④供应链安全',
      kpi: '拦截一切违规。',
      constitution: '全部铁则',
      defense: '铁则就是铁则，但分绝对违规 vs 需授权。',
    },
  ],
  pageCore: [
    { id: 'repo-home', path: '/', name: '仓库首页（首屏）' },
    { id: 'readme', path: '/readme', name: 'README 全文' },
    { id: 'install', path: '/install', name: 'Installation/Quickstart' },
    { id: 'usage', path: '/usage', name: 'Usage/Examples' },
    { id: 'docs', path: '/docs', name: 'Docs' },
    { id: 'contributing', path: '/contributing', name: 'Contributing' },
    { id: 'license', path: '/license', name: 'License' },
    { id: 'issues', path: '/issues', name: 'Issues（活跃度）' },
    { id: 'releases', path: '/releases', name: 'Releases' },
  ],
  modelTiers: [
    { tier: 'T1', hint: 'README 的核心段落（快速开始/示例）', n: 8 },
    { tier: 'T2', hint: 'README 的中段（文档/配置/进阶）', n: 6 },
    { tier: 'T3', hint: 'README 的尾部（贡献/License/FAQ）', n: 4 },
  ],
  pageLongtail: [
    { id: 'lt-topics', name: 'Topics/徽章', path: '/topics' },
    { id: 'lt-package', name: 'package.json（可安装性）', path: '/package' },
    { id: 'lt-mobile', name: '移动端视图', path: '/mobile' },
    { id: 'lt-faq', name: 'FAQ', path: '/faq' },
    { id: 'lt-mobile2', name: '移动端滚动', path: '/mobile-scroll' },
    { id: 'lt-actions', name: 'CI/Actions 页（可信度）', path: '/actions' },
    { id: 'lt-new-issue', name: '新建 Issue 模板', path: '/issues/new' },
    { id: 'lt-pulse', name: '活跃度 Pulse', path: '/pulse' },
  ],
}
