// SaaS 场景配置 —— 特点：注册转化/定价/留存 是核心
export default {
  name: "我的 SaaS",
  siteUrl: "http://localhost:3000",
  workDir: ".",
  memoryDir: "reports/iterate",
  dims: [
    { k: 'D', name: '注册转化', q: '访客能否快速注册/开始试用', veto: false },
    { k: 'C', name: '内容质量', q: 'landing 文案/案例是否可信', veto: false },
    { k: 'M', name: '变现', q: '定价/升级/账单是否清晰', veto: false },
    { k: 'T', name: '数据可信', q: '用户数/案例/定价是否可验证', veto: true, vm: 4 },
    { k: 'R', name: '合规', q: '隐私/条款/订阅取消', veto: true, vm: 4 },
    { k: 'S', name: '可维护', q: '功能迭代维护成本低', veto: true, vm: 3 },
    { k: 'F', name: '目标一致', q: '是否服务激活/留存', veto: true, vm: 1 },
    { k: 'P', name: '性能', q: '首屏/app 加载', veto: false },
    { k: 'U', name: '体验', q: 'onboarding/引导/移动端', veto: false },
    { k: 'G', name: '增长', q: 'SEO/PLG 自传播', veto: false },
  ],
  extremeWords: ['最大', '最强', '最好', 'no.1', 'the best', 'leading', '唯一', '革命性', '颠覆性'],
  roles: [
    {
      key: 'prospect', name: '潜在客户', w: { D: 3 }, scope: ['all'],
      identity: '想评估你的 SaaS 是否值得用的访客：看卖点→看定价→看案例→注册试用。',
      vision: '我评估“值不值得试”：价值主张清楚吗？定价透明吗？注册后能不能自己跑起来？',
      checklist: '①价值主张首屏说清 ②定价/对比是否透明 ③案例/评价是否可信 ④注册流程是否顺畅 ⑤试用后能否独立上手',
      kpi: '发现“看完不敢注册”或“注册后迷路”的。',
      constitution: '价值主张清晰·定价透明·引导到位',
      defense: '别把“功能少”当缺点。只报“说不清/不敢注册”的。',
    },
    {
      key: 'maintainer', name: '维护者', w: { S: 3 }, scope: ['all'], judge: true, veto: 'S',
      identity: '站点的唯一运营者。评估这条改动让我每天多花几分钟。',
      vision: '可持续性：功能要人工维护吗？会成负担吗？',
      checklist: '①维护成本 ②数据源稳定 ③自动化空间 ④失败风险 ⑤值不值',
      kpi: '驳回高维护改动。',
      constitution: '单人可持续',
      defense: '别把一次性配置当高维护。',
    },
  ],
  pageCore: [
    { id: 'home', path: '/', name: '首页' },
    { id: 'pricing', path: '/pricing', name: '定价' },
    { id: 'signup', path: '/signup', name: '注册' },
    { id: 'features', path: '/features', name: '功能' },
    { id: 'case', path: '/customers', name: '案例' },
    { id: 'blog', path: '/blog', name: '博客' },
    { id: 'about', path: '/about', name: '关于' },
  ],
  modelTiers: [
    { tier: 'T1', hint: '从首页挑一个核心功能/案例页', n: 8 },
    { tier: 'T2', hint: '从导航挑一个普通功能页', n: 6 },
    { tier: 'T3', hint: '从底部挑一个旧功能/归档页', n: 3 },
  ],
  pageLongtail: [
    { id: 'lt-pricing-enterprise', name: '企业定价', path: '/pricing/enterprise' },
    { id: 'lt-security', name: '安全页', path: '/security' },
    { id: 'lt-integrations', name: '集成', path: '/integrations' },
    { id: 'lt-changelog', name: '更新日志', path: '/changelog' },
    { id: 'lt-404', name: '404页', path: '/nonexistent' },
  ],
}
